<?php

namespace Apps\Tms\Components\System\Filters;

use Apps\Tms\Packages\Adminltetags\Traits\DynamicTable;
use System\Base\BaseComponent;

class FiltersComponent extends BaseComponent
{
    use DynamicTable;

    protected $filters;

    protected $components;

    public function initialize()
    {
        $this->filters = $this->basepackages->filters;
    }

    /**
     * @acl(name=view)
     */
    public function viewAction()
    {
        if ($this->request->isGet()) {
            if ($this->app['id'] == 1) {
                $components = $this->modules->components->components;
            } else {
                $components = $this->modules->components->getComponentsForAppType($this->app['app_type']);
            }

            foreach ($components as $key => $component) {
                $components[$key]['name'] = $component['name'] . ' (' . $component['category'] . ')';
            }

            $this->view->components = $components;
        }

        if (isset($this->getData()['id'])) {
            if ($this->getData()['id'] != 0) {
                $filter = $this->filters->getById($this->getData()['id']);

                if (!$filter) {
                    return $this->throwIdNotFound();
                }

                $this->view->filter = $filter;
            }

            $this->view->pick('filters/view');

            return;
        }

        if ($this->request->isPost()) {
            $replaceColumns =
                function ($dataArr) {
                    if ($dataArr && is_array($dataArr) && count($dataArr) > 0) {
                        return $this->replaceColumns($dataArr);
                    }

                    return $dataArr;
                };
        } else {
            $replaceColumns = null;
        }

        $controlActions =
            [
                'actionsToEnable'       =>
                [
                    'edit'      => 'system/filters',
                    'remove'    => 'system/filters/remove'
                ]
            ];

        $this->generateDTContent(
            $this->filters,
            'system/filters/view',
            null,
            ['name', 'app_type', 'component_id', 'filter_type', 'is_default', 'auto_generated'],
            true,
            ['name', 'app_type', 'component_id', 'filter_type', 'is_default', 'auto_generated'],
            $controlActions,
            ['component_id'=>'Component (id)'],
            $replaceColumns,
            'name'
        );

        $this->view->pick('filters/list');
    }

    protected function replaceColumns($dataArr)
    {
        foreach ($dataArr as $dataKey => &$data) {
            $data = $this->formatComponentId($dataKey, $data);
            $data = $this->formatFilterType($dataKey, $data);
            $data = $this->formatIsDefault($dataKey, $data);
            $data = $this->formatAutogenerated($dataKey, $data);
        }

        return $dataArr;
    }

    protected function formatComponentId($rowId, $data)
    {
        if (!isset($this->components[$data['component_id']])) {
            $component = $this->modules->components->getById($data['component_id']);
        } else {
            $component = $this->components[$data['component_id']];
        }

        if ($component) {
            $data['component_id'] = $component['name'] . ' (' . $component['id'] . ')';
        }

        return $data;
    }

    protected function formatFilterType($rowId, $data)
    {
        if ($data['filter_type'] == '0') {
            $data['filter_type'] = '<span class="badge badge-secondary text-uppercase">System (' . $data['filter_type'] . ')</span>';
        } else if ($data['filter_type'] == '1') {
            $data['filter_type'] = '<span class="badge badge-primary text-uppercase">User (' . $data['filter_type'] . ')</span>';
        }

        return $data;
    }

    protected function formatIsDefault($rowId, $data)
    {
        if ($data['is_default'] == '0') {
            $data['is_default'] = '<span class="badge badge-secondary text-uppercase">No (' . $data['is_default'] . ')</span>';
        } else if ($data['is_default'] == '1') {
            $data['is_default'] = '<span class="badge badge-primary text-uppercase">Yes (' . $data['is_default'] . ')</span>';
        }

        return $data;
    }

    protected function formatAutogenerated($rowId, $data)
    {
        if ($data['auto_generated'] == '0') {
            $data['auto_generated'] = '<span class="badge badge-secondary text-uppercase">No (' . $data['auto_generated'] . ')</span>';
        } else if ($data['auto_generated'] == '1') {
            $data['auto_generated'] = '<span class="badge badge-primary text-uppercase">Yes (' . $data['auto_generated'] . ')</span>';
        }

        return $data;
    }

    /**
     * @acl(name=add)
     */
    public function addAction()
    {
        $this->requestIsPost();

        if ($this->app['id'] === 1) {
            $this->filters->addFilter($this->postData());

            $this->view->filters = $this->filters->packagesData->filters;
        } else {
            //Adding clone in add as cloning requires add permission so both add and clone can be performed in same action.
            if (isset($this->postData()['clone']) && $this->postData()['clone']) {
                $this->filters->cloneFilter($this->postData());
            } else {
                $this->filters->addFilter($this->postData());
            }

            if (isset($this->postData()['component_id'])) {
                $this->view->filters = $this->filters->packagesData->filters;
            }
        }

        $this->addResponse(
            $this->filters->packagesData->responseMessage,
            $this->filters->packagesData->responseCode
        );
    }

    /**
     * @acl(name=update)
     */
    public function updateAction()
    {
        $this->requestIsPost();

        $this->filters->updateFilter($this->postData());

        if ($this->app['id'] == 1) {
            $this->view->filters = $this->filters->packagesData->filters;
        } else {
            if (isset($this->postData()['component_id'])) {
                $this->view->filters = $this->filters->packagesData->filters;
            }
        }

        $this->addResponse(
            $this->filters->packagesData->responseMessage,
            $this->filters->packagesData->responseCode
        );
    }

    protected function cloneAction()
    {
        $this->requestIsPost();

        $this->filters->cloneFilter($this->postData());

        $this->view->filters = $this->filters->packagesData->filters;

        $this->addResponse(
            $this->filters->packagesData->responseMessage,
            $this->filters->packagesData->responseCode
        );
    }

    /**
     * @acl(name=remove)
     */
    public function removeAction()
    {
        $this->requestIsPost();

        $removeFilter = $this->filters->removeFilter($this->postData());

        $this->addResponse(
            $this->filters->packagesData->responseMessage,
            $this->filters->packagesData->responseCode
        );

        if ($removeFilter) {
            if ($this->app['id'] === 1) {
                $this->view->filters = $this->filters->packagesData->filters;
            } else {
                if (isset($this->postData()['component_id'])) {
                    $this->view->filters = $this->filters->packagesData->filters;
                }
            }
        }
    }

    public function getdefaultfilterAction()
    {
        $this->requestIsPost();

        if ($this->filters->getDefaultFilter($this->postData()['component_id'])) {
            $this->view->defaultFilter = $this->filters->packagesData->defaultFilter;
        }

        $this->addResponse(
            $this->filters->packagesData->responseMessage,
            $this->filters->packagesData->responseCode
        );
    }
}
